import type { EditorThemeClasses } from 'lexical';

export const obsidianTheme: EditorThemeClasses = {
	paragraph: 'cm-line',
	heading: {
		h1: 'cm-header cm-header-1',
		h2: 'cm-header cm-header-2',
		h3: 'cm-header cm-header-3',
		h4: 'cm-header cm-header-4',
		h5: 'cm-header cm-header-5',
		h6: 'cm-header cm-header-6',
	},
	text: {
		bold: 'cm-strong',
		italic: 'cm-em',
		underline: 'cm-underline',
		strikethrough: 'cm-strikethrough',
		code: 'cm-inline-code',
	},
	link: 'cm-link cm-underline',
	list: {
		ul: 'cm-list',
		ol: 'cm-list',
		listitem: 'cm-list-item',
		nested: { listitem: 'cm-list-item-nested' },
		checklist: 'cm-checklist',
		listitemChecked: 'cm-list-item-checked',
		listitemUnchecked: 'cm-list-item-unchecked',
	},
	hashtag: 'cm-hashtag',
	quote: 'cm-quote',
	code: 'cm-codeblock',
	table: 'cm-table',
	tableRow: 'cm-table-row',
	tableCell: 'cm-table-cell',
	tableCellHeader: 'cm-table-cell-header',
	codeHighlight: {
		atrule: 'tok-atrule',
		attr: 'tok-attr',
		boolean: 'tok-boolean',
		builtin: 'tok-builtin',
		cdata: 'tok-cdata',
		char: 'tok-char',
		class: 'tok-class',
		'class-name': 'tok-class-name',
		comment: 'tok-comment',
		constant: 'tok-constant',
		deleted: 'tok-deleted',
		doctype: 'tok-doctype',
		entity: 'tok-entity',
		function: 'tok-function',
		important: 'tok-important',
		inserted: 'tok-inserted',
		keyword: 'tok-keyword',
		namespace: 'tok-namespace',
		number: 'tok-number',
		operator: 'tok-operator',
		prolog: 'tok-prolog',
		property: 'tok-property',
		punctuation: 'tok-punctuation',
		regex: 'tok-regex',
		selector: 'tok-selector',
		string: 'tok-string',
		symbol: 'tok-symbol',
		tag: 'tok-tag',
		url: 'tok-url',
		variable: 'tok-variable',
	},
};
